#! /bin/bash
# vim: ft=sh
#
# simple compile file
# Usage:
# ./ompiler hello.c
# hello.c > dist/hello.out

source=$1
target=${2:-$(echo $source | awk -F '.' '{print $1}')}
suffix='out'

if [ -e $source ]; then
    gcc -Wall $source -o "dist/$target.$suffix"
fi
